### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by mmueller-kaffeeschluerfercom** [hegdi/libldacdec#1]
Hi

I'm trying to compile libldacdec. I started with
```
git clone https://github.com/hegdi/libldacdec.git
cd libldacdec
git submodule init
git submodule update
make
```
this is the output:

```
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src   -c -o ldacdec.o ldacdec.c
ldacdec.c: In function ‘main’:
ldacdec.c:68:9: warning: unused variable ‘blockId’ [-Wunused-variable]
     int blockId = 0;
         ^~~~~~~
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o libldacdec.o libldacdec.c
libldacdec.c: In function ‘ldacNullPacket’:
libldacdec.c:520:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o bit_allocation.o bit_allocation.c
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o huffCodes.o huffCodes.c
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o bit_reader.o bit_reader.c
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o utility.o utility.c
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o imdct.o imdct.c
gcc -MMD -MP -O3 -g -march=native -DVERSION="\"bbba\"" -std=gnu11 -Wall -Wextra -Ilibldac/inc -Ilibldac/src -fpic   -c -o spectrum.o spectrum.c
gcc -L. -Wl,-rpath=. -shared -fpic -Wl,-soname,libldacdec.so.1 -o libldacdec.so libldacdec.o bit_allocation.o huffCodes.o bit_reader.o utility.o imdct.o spectrum.o -lm -lldacdec -lsndfile
./libldacdec.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Makefile:44: recipe for target 'libldacdec.so' failed
make: *** [libldacdec.so] Error 1

```

I'm trying to compile on debian stretch. Am I missing something? Any help appreciated! Thanks a lot.

**Comment by mringwal** [comment]
try https://stackoverflow.com/questions/5713894/file-not-recognized-file-truncated-gcc-error

**Comment by mmueller-kaffeeschluerfercom** [comment]
I also found this page before posting the issue, but in my case it did't help, as there is nothing to delete... It happens on a fresh build, as well as after deleting all .o files...

**Comment by mmueller-kaffeeschluerfercom** [comment]
I just managed to compile it by manually invoking gcc without the option -lldacdec to compile the libldacdec.so, then copy the file to libldacdec.so.1 and then invoke 'make' again. But I don't know how to change the Makefile to reflect this behaviour.

**Comment by mringwal** [comment]
hm.. if you like, please try my fork, which provides an automake-based build: https://github.com/mringwal/libldacdec

**Comment by hegdi** [comment]
Well, you can change
https://github.com/hegdi/libldacdec/blob/bbba07ce8d81da7f1ddad6526ad02af1bd3e60fb/Makefile#L24
to
```make
    all: libldacdec.so ldacdec ldacenc
```
you are getting that while building on Linux?

**Comment by mmueller-kaffeeschluerfercom** [comment]
Thanks, changing line 24 works! Yes, it's on debian stretch.

**Comment by mmueller-kaffeeschluerfercom** [comment]
> hm.. if you like, please try my fork, which provides an automake-based build: https://github.com/mringwal/libldacdec

Thanks for the hint. Unfortunately, on my system, this does not work out of the box. And as I managed to get it compiled, I didn't look further into this. Thanks anyway.

**Comment by XPRAMT** [comment]
Help
![螢幕擷取畫面 2023-12-16 135353](https://github.com/hegdi/libldacdec/assets/34093551/e6b7f366-01c3-4aa5-a441-9f7abe7ff0b1)

**Comment by mringwal** [comment]
Well, it looks you don't have the C Compiler 'gcc' installed. Please setup your system so you can compile C sources.

**Comment by XPRAMT** [comment]
> Well, it looks you don't have the C Compiler 'gcc' installed. Please setup your system so you can compile C sources.

Okay, thank you!

**Comment by ValeZAA** [comment]
> Well, you can change
> 
> https://github.com/hegdi/libldacdec/blob/bbba07ce8d81da7f1ddad6526ad02af1bd3e60fb/Makefile#L24
> 
> 
> to
> ```makefile
>     all: libldacdec.so ldacdec ldacenc
> ```
> 
> you are getting that while building on Linux?

That does not help. You need to compile stuff into libldacdec.so.1, then create libldacdec.so that is linked to it. Or more easily in this case just `mv libldacdec.so libldacdec.so.1`

Maybe you did not notice, but make clean does not erase libldacdec.so.1

**Comment by ValeZAA** [comment]
ln -s ./libldacdec.so  ./libldacdec.so.1

you need to do. LOL
